### ISSUE TITLE
modules: or everything in one directory

### ISSUE THREAD

**Issue by voku** [chubbyphp/petstore#26]
Hi I only take a quick look into this example, but I see one directory for all "Models" and all other classes that are related to this Model e.g. "Repository" are also in one big directory, this is working for a small example application, but how do you build a bigger one, or do you use a different file structure in different cases? Thanks for your work and thanks for open sourcing this. :+1:

**Comment by dominikzogg** [comment]
I would suggest something like that: Everything that is generic (for your usecase) stays on top, the rest within an additional folder level:

```
Collection
    AbstractCollection
    CollectionInterface
Config
    ...
Factory
    CollectionFactoryInterface
    ModelFactoryInterface
Mapping
    Serialization
        AbstractCollectionMapping
        AbstractModelMapping
Pet
    Collection
        PetCollection
    Factory
        PetFactory.php
        PetCollectionFactory.php
    Mapping
        Deserialization
            ...
        Orm
            ...
        Serialization
            PetCollectionMapping
            PetMapping
            VaccinationMapping
        Validation:
            ...
```

**Comment by voku** [comment]
Thanks for the answer. 

Where do you store "Pet" related services? And "VaccinationMapping" are only code-past error, or?

**Comment by dominikzogg** [comment]
Within `app/Pet/**/*.php`, for example `app/Pet/ApiClient/ExternalApi.php` or `app/Pet/Provider/AdditionalInformationProvider.php` (sorry for the bad naming). 

I the current structure i see the Vaccination as a part of the entity (like a document). If the vaccination would an entity by itself, referenced to the pet with some information when and where its done, its up to you if you count that to the same domain of your application.
